<?php
   include_once('./includes/headerNav.php');
  include "includes/config.php";

?>



<div class="overlay" data-overlay></div>
<!--
    - HEADER
  -->

<header>
  <!-- top head action, search etc in php -->
  <?php require_once './includes/topheadactions.php'; ?>

  <!-- mobile nav in php -->
  <?php require_once './includes/mobilenav.php'; ?>

</header>

<!--
    - MAIN
  -->

<main>

  <div class="product-container">
    <div class="container">
      <!--
          - SIDEBAR
        -->
      <!-- CATEGORY SIDE BAR MOBILE MENU -->
      <?php require_once './includes/categorysidebar.php'; ?>
      <!-- ############################# -->

      <div class="product-box">
        <!-- get id and url for each category and display its dat from table her in this secton -->
        <div class="product-main">

          <h2 class="title">
            Search: 
            <?php 
              // Get Item name searching for
              if(isset($_POST['search']))
              {
                echo $_POST['search'];
              }
             ?> 
          </h2>

          <div class="product-grid">

            <!-- display data from table new products -->

            <?php
            //Very important SEO friendly code generated by myself (practices)

            if(isset($_POST['submit']) AND !(empty($_POST['search'])) OR isset($_POST['catag'])) {

              if(isset($_GET['catag'])) {
                $seacrh_term = mysqli_real_escape_string($conn, $_GET['catag']);
              } else {
                $seacrh_term = mysqli_real_escape_string($conn, $_POST['search']);
              }

            

            if (isset($_GET['page'])){
              $page = $_GET['page'];
            } else {
              $page = 1;
            }

            // define how much data to show in a page from database
            $limit = 8;
            // define from which row to start extracting data from database
            $offset = ($page - 1) * $limit;

              //making search_term string to array each value separated by space
              $search_term_array = explode(" ",$seacrh_term);

              // Loop over each item
              for($search=0; $search<sizeof($search_term_array); $search++){
              
                $array_length = sizeof($search_term_array);
                
                if($array_length > 1) {

                  $search_query = "SELECT * FROM products WHERE products.product_title LIKE '%{$search_term_array[$search]}%' AND products.product_catag LIKE '%{$search_term_array[$search+1]}%' ORDER BY products.product_id DESC LIMIT {$offset},{$limit}";

                }

                if($array_length == 1) {

                  $search_query = "SELECT * FROM products WHERE  products.product_title LIKE '%{$search_term_array[$search]}%' OR products.product_catag LIKE '%{$search_term_array[$search]}%' ORDER BY products.product_id DESC LIMIT {$offset},{$limit}";

                }

                break;
              }

              // Execute search query
              $search_result = $conn->query($search_query);
              $new_product_counter = 1;

            // Query used earlier 
            // $search_query = "SELECT * FROM PRODUCT WHERE product.name LIKE '%$get_seach_value%' ";
            // $run_search = mysqli_query($connect,$search_query);
            if($search_result->num_rows > 0) {

            
            while ($row = mysqli_fetch_assoc($search_result)) {

            ?>
              <!-- display all category products -->
              <div class="showcase">
                <div class="showcase-banner">
                  <img src="./admin/upload/<?php
                                                      echo $row['product_img']
                                                      ?>" alt="Mens Winter Leathers Jackets" width="300" class="product-img default" />
                  <img src="./admin/upload/<?php
                                                      echo $row['product_img']
                                                      ?>" alt="search result images" width="300" class="product-img hover" />
                  <!-- Applying coditions on dicount and sale tags  -->
                  <!--  -->
                

                  <div class="showcase-actions">
                    <button class="btn-action">
                      <ion-icon name="heart-outline"></ion-icon>
                    </button>

                    <button class="btn-action">
                      <ion-icon name="eye-outline">

                      </ion-icon>
                    </button>

                    <button class="btn-action">
                      <ion-icon name="repeat-outline"></ion-icon>
                    </button>

                    <button class="btn-action">
                      <ion-icon name="bag-add-outline"></ion-icon>
                    </button>
                  </div>
                </div>

                <div class="showcase-content">
                  <a href="./viewdetail.php?id=<?php echo $row['product_id'] ?>&category=<?php $row['category_id'] ?>" class="showcase-category">
                    <?php echo $row['product_title'] ?>
                  </a>

                  <a href="./viewdetail.php?id=<?php echo $row['product_id'] ?>&category=<?php $row['category_id'] ?>">
                    <h3 class="showcase-title">
                      <?php echo $row['product_desc'] ?>
                    </h3>
                  </a>

                  <div class="showcase-rating">
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                  </div>

                  <div class="price-box">
                    <p class="price">
                      $<?php echo $row['discounted_price'] ?>
                    </p>
                    <del>
                      $<?php echo $row['product_price'] ?>
                    </del>
                  </div>
                </div>
              </div>

            <?php
              $new_product_counter = $new_product_counter + 1;
             }} else { 
              echo "<h4 style='color:red; margin-left:8%;border:1px solid aliceblue'>"."No record found"."</h4>";
            }
             $conn->close(); 
            ?>

            <!--  -->
          </div>
        </div>
      </div>
    </div>
  </div>

<!--Pagination-->
<div class="pag-cont-search">
<?php
                include "includes/config.php"; 

               // Pagination btn using php with active effects 

                $sql1 = "SELECT * FROM products";
                $result1 = mysqli_query($conn, $sql1) or die("Query Failed.");

                if(mysqli_num_rows($result1) > 0){

                  $total_products = mysqli_num_rows($search_result);
                  $total_page = ceil($total_products / $limit);

                  echo "<div class='pagination'>";  
          
                  for($i=1; $i<=$total_page; $i++){

                    //important this is for active effects that denote in which page you are in current position
                    if($page==$i){
                      $active = "active";
                    }else{
                      $active = "";
                    }

                        echo "<a href='search.php?page={$i}' class='{$active}'>".$i."</a>";
                  }
            
                }
                echo "</div>";

               } //main if
               else {
                 echo "<h4 style='color:red; margin-left:8%;border:1px solid aliceblue'>"."ERR_Insert on Search"."</h4>";
               }
               ?>
	
</div>


</main>

<?php require_once './includes/footer.php'; ?>
